# BROWSER SELECTION
browser=chrome

# APPLICATION URL
url=https://www.demoblaze.com/

# APPLICATION CREDENTIAL
username=karthick1502
password=Toffee@1502

# CLEINT DETIALS
name=KARTHICK
country=INDIA
city=CHENNAI
card=122673839293773
month=MARCH
year=2025